In [4]:
import numpy as np

score = np.array([
    [80, 89, 86, 68, 79],
    [80, 89, 86, 68, 79],
    [80, 89, 86, 68, 79],
    [80, 89, 86, 68, 79]])

In [31]:
score

array([[80, 89, 86, 68, 79],
       [80, 89, 86, 68, 79],
       [80, 89, 86, 68, 79],
       [80, 89, 86, 68, 79]])

In [10]:
score.shape

(4, 5)

In [13]:
score.ndim

2

In [14]:
score.size

20

In [15]:
score.dtype

dtype('int32')

In [16]:
score.itemsize

4

In [42]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
b = np.array([1, 2, 3, 4])
c = np.array([[
    [1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [33]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
b

array([1, 2, 3, 4])

In [43]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])